config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'trades', to: 'trades#index'

  devise_for :users
  get 'lists/of_currencies'

  get 'lists/of_pairs'

  get 'lists/of_trios'

  get 'pages/home'
  root 'pages#home'

  resources :arbitrages
  # get 'arbitrages', to: 'arbitrages#index'

  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arbitrage.rb
class Arbitrage < ApplicationRecord
  belongs_to :trio
  belongs_to :first_order_book, class_name: 'OrderBook'
  belongs_to :second_order_book, class_name: 'OrderBook'
  belongs_to :third_order_book, class_name: 'OrderBook'
  has_many :trades
end

app/models/currency.rb
class Currency < ApplicationRecord

  has_many :first_currency_pairs, foreign_key: "first_currency_id", class_name: "Pair"
  has_many :second_currency_pairs, foreign_key: "second_currency_id", class_name: "Pair"

  has_many :first_currency_trios, foreign_key: "first_currency_id", class_name: "Trio"
  has_many :second_currency_trios, foreign_key: "second_currency_id", class_name: "Trio"
  has_many :third_currency_trios, foreign_key: "third_currency_id", class_name: "Trio"

end

app/models/order_book.rb
class OrderBook < ApplicationRecord
  serialize :bid_hash
  serialize :ask_hash

  belongs_to :pair

  has_many :first_order_book_arbitrages, foreign_key: "first_order_book_id", class_name: "Arbitrage"
  has_many :second_order_book_arbitrages, foreign_key: "second_order_book_id", class_name: "Arbitrage"
  has_many :third_order_book_arbitrages, foreign_key: "third_order_book_id", class_name: "Arbitrage"

end

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :first_currency, class_name: 'Currency'
  belongs_to :second_currency, class_name: 'Currency'

  has_many :order_books
  has_many :trades
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :pair
  belongs_to :arbitrage
end

app/models/trio.rb
class Trio < ApplicationRecord
  belongs_to :first_currency, class_name: 'Currency'
  belongs_to :second_currency, class_name: 'Currency'
  belongs_to :third_currency, class_name: 'Currency'

  has_many :arbitrages

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :sign_up_code
  validates :sign_up_code,
    on: :create,
    presence: true,
    inclusion: { in: [ENV["SIGN_UP_CODE"]] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo,:sign_up_code])
  end
end

app/controllers/arbitrages_controller.rb
class ArbitragesController < ApplicationController

  before_action :authenticate_user!

  def index
    @order_book_count = OrderBook.all.count
    # @barrier = 1.0076 #Limite de rentabilité
    @barrier = 1.05
    @arbitrage_selection = Arbitrage.where("raw_ratio > ?",@barrier)
  end

  def show
    @arbitrage = Arbitrage.find(params[:id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!

  def of_currencies
    @currencies = Currency.all
  end

  def of_pairs
    @pairs = Pair.all
    @currencies = Currency.all
  end

  def of_trios
    @trios = Trio.all
    @currencies = Currency.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @trades = Trade.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def cp(path)
    'active' if current_page?(path)
  end

end

app/helpers/arbitrages_helper.rb
module ArbitragesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/arbitrages/index.html.erb
<div class="container">
  <h1>Analyse des arbitrages</h1>

  <p>Nous avons trouvé <%= @arbitrage_selection.count %> opportunités d'abritrage !</p>
  <p>Arbitrages sélectionnés pour une barrière de <%= @barrier %>.</p>

  <table class="table table-condensed table-hover" id="arbitrages">
    <thead>
      <tr>
        <th>Id</th>
        <th>Trio</th>
        <th>Worst Ratio</th>
        <th>Raw Ratio</th>
        <th>Time</th>
        <th>+</th>
      </tr>
    </thead>
    <tbody>
      <% @arbitrage_selection.each do |arbitrage| %>
      <tr>
        <td><%= arbitrage.id %></td>
        <td><%= arbitrage.trio.first_currency.code %> > <%= arbitrage.trio.second_currency.code %> > <%= arbitrage.trio.third_currency.code %></td>
        <td><%= arbitrage.worst_ratio != nil ? (arbitrage.worst_ratio.round(4)) : nil %></td>
        <td><%= arbitrage.raw_ratio.round(4) %></td>
        <td><%= arbitrage.created_at %></td>
        <td><%= link_to 'Details', arbitrage %></td>
      </tr>
      
      <% end %>
    </tbody>
  </table>
    
</div>

app/views/arbitrages/show.html.erb
<div class="container">
  
  <h1>L'arbitrage identifé : <%= @arbitrage.raw_ratio.round(2) %></h1>
  <ul>
    <li><b>ID</b> : <%= @arbitrage.id %> </li>
    <li><b>Trio</b> : <%= @arbitrage.trio.first_currency.code %> > <%= @arbitrage.trio.second_currency.code %> > <%= @arbitrage.trio.third_currency.code %></li>
    <li><b>Time</b> : <%= @arbitrage.created_at %></li>
    <li><b>Raw Ratio</b> (before transaction costs) : <%= @arbitrage.raw_ratio.round(5) %></li>
    <li><b>Worst Ratio</b> (before transaction costs) : <%= @arbitrage.worst_ratio.round(5) %></li>
  </ul>

  <h5>Formules de calculs</h5>
  <ul>
    <li>Raw Ratio
      <ul>
        <li>La formule utilisée pour calculer le raw ratio est la suivante : 1/(dernier_ask 1ère paire) * 1/(dernier_ask 2ème paire) * (1er bid de la 3ème paire)</li>
        <li>Seront highlighté en vert les valeurs des orders books qui sont utilisés pour calculer le ratio.</li>
      </ul>
    </li>
    <li>Worst Ratio
      <ul>
        <li>La formule utilisée pour calculer le raw ratio est la suivante : 1/(premier_ask 1ère paire) * 1/(premier_ask 2ème paire) * (Dernier bid de la 3ème paire)</li>
        <li>Seront highlighté en rouge les valeurs des orders books qui sont utilisés pour calculer le ratio.</li>
      </ul>
    </li>
  </ul>
    

  <h1>Analyse des 3 paires de transactions</h1>

    <h2>1ère paire : <%= @arbitrage.trio.first_currency.code %> > <%= @arbitrage.trio.second_currency.code %> </h2>
      <h3>Order Book</h3>
        <table class="table table-bordered table-condensed table-hover">
          <tr class="active">
            <th colspan="3">Bid</th>
            <th colspan="3">Ask</th>
          </tr>
          <tr class="active">
            <th class="rank_column">Rank</th>
            <th>Price</th>
            <th>Volume</th>
            <th class="rank_column">Rank</th>
            <th>Price</th>
            <th>Volume</th>
          </tr>
        <tr>
          <td class="rank_column">1</td>
          <td><%= @arbitrage.first_order_book.bid_hash[0][0].to_f.round(4) %></td>
          <td><%= @arbitrage.first_order_book.bid_hash[0][1].round(4) %></td>
          <td class="danger rank_column">1</td>
          <td class="danger"><%= @arbitrage.first_order_book.ask_hash[0][0].to_f.round(10) %></td>
          <td class="danger"><%= @arbitrage.first_order_book.ask_hash[0][1].round(4) %></td>
        </tr>
        <% rank = 2 %>
        <% 8.times do %>
          <tr>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.first_order_book.bid_hash[rank-1][0].to_f.round(4) %></td>
            <td><%= @arbitrage.first_order_book.bid_hash[rank-1][1].round(4) %></td>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.first_order_book.ask_hash[rank-1][0].to_f.round(4) %></td>
            <td><%= @arbitrage.first_order_book.ask_hash[rank-1][1].round(4) %></td>
          </tr>
          <% rank += 1 %>
        <% end %>
        <tr>
          <td class="rank_column">10</td>
          <td><%= @arbitrage.first_order_book.bid_hash[9][0].to_f.round(4) %></td>
          <td><%= @arbitrage.first_order_book.bid_hash[9][1].round(4) %></td>
          <td class="success rank_column">10</td>
          <td class="success"><%= @arbitrage.first_order_book.ask_hash[9][0].to_f.round(10) %></td>
          <td class="success"><%= @arbitrage.first_order_book.ask_hash[9][1].round(4) %></td>
        </tr>
        </table>

    <h2>2ème paire : <%= @arbitrage.trio.second_currency.code %> > <%= @arbitrage.trio.third_currency.code %> </h2>
      <h3>Order Book</h3>
        <table class="table table-bordered table-condensed table-hover">
          <tr class="active">
            <th colspan="3">Bid</th>
            <th colspan="3">Ask</th>
          </tr>
          <tr class="active">
            <th>Rank</th>
            <th>Price</th>
            <th>Volume</th>
            <th>Rank</th>
            <th>Price</th>
            <th>Volume</th>
          </tr>
        <tr>
          <td class="rank_column">1</td>
          <td><%= @arbitrage.second_order_book.bid_hash[0][0].to_f.round(4) %></td>
          <td><%= @arbitrage.second_order_book.bid_hash[0][1].round(4) %></td>
          <td class="danger rank_column">1</td>
          <td class="danger"><%= @arbitrage.second_order_book.ask_hash[0][0].to_f.round(10) %></td>
          <td class="danger"><%= @arbitrage.second_order_book.ask_hash[0][1].round(4) %></td>
        </tr>
        <% rank = 2 %>
        <% 8.times do %>
          <tr>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.second_order_book.bid_hash[rank-1][0].to_f.round(8) %></td>
            <td><%= @arbitrage.second_order_book.bid_hash[rank-1][1].round(4) %></td>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.second_order_book.ask_hash[rank-1][0].to_f.round(8) %></td>
            <td><%= @arbitrage.second_order_book.ask_hash[rank-1][1].round(4) %></td>
          </tr>
          <% rank += 1 %>
        <% end %>
        <tr>
          <td class="rank_column">10</td>
          <td><%= @arbitrage.second_order_book.bid_hash[9][0].to_f.round(8) %></td>
          <td><%= @arbitrage.second_order_book.bid_hash[9][1].round(4) %></td>
          <td class="success rank_column">10</td>
          <td class="success"><%= @arbitrage.second_order_book.ask_hash[9][0].to_f.round(8) %></td>
          <td class="success"><%= @arbitrage.second_order_book.ask_hash[9][1].round(4) %></td>
        </tr>
        </table>

    <h2>3ème paire : <%= @arbitrage.trio.first_currency.code %> > <%= @arbitrage.trio.third_currency.code %> </h2>
      <h3>Order Book</h3>
        <table class="table table-bordered table-condensed table-hover">
          <tr class="active">
            <th colspan="3">Bid</th>
            <th colspan="3">Ask</th>
          </tr>
          <tr class="active">
            <th>Rank</th>
            <th>Price</th>
            <th>Volume</th>
            <th>Rank</th>
            <th>Price</th>
            <th>Volume</th>
          </tr>
        <tr>
          <td class="success rank_column">1</td>
          <td class="success"><%= @arbitrage.third_order_book.bid_hash[0][0].to_f.round(8) %></td>
          <td class="success"><%= @arbitrage.third_order_book.bid_hash[0][1].round(4) %></td>
          <td class="rank_column">1</td>
          <td><%= @arbitrage.third_order_book.ask_hash[0][0].to_f.round(8) %></td>
          <td><%= @arbitrage.third_order_book.ask_hash[0][1].round(4) %></td>
        </tr>
        <% rank = 2 %>
        <% 8.times do %>
          <tr>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.third_order_book.bid_hash[rank-1][0].to_f.round(8) %></td>
            <td><%= @arbitrage.third_order_book.bid_hash[rank-1][1].round(4) %></td>
            <td class="rank_column"><%= rank %></td>
            <td><%= @arbitrage.third_order_book.ask_hash[rank-1][0].to_f.round(8) %></td>
            <td><%= @arbitrage.third_order_book.ask_hash[rank-1][1].round(4) %></td>
          </tr>
          <% rank += 1 %>
        <% end %>
        <tr>
          <td class="danger rank_column">10</td>
          <td class="danger"><%= @arbitrage.third_order_book.bid_hash[9][0].to_f.round(8) %></td>
          <td class="danger"><%= @arbitrage.third_order_book.bid_hash[9][1].round(4) %></td>
          <td class="rank_column">10</td>
          <td><%= @arbitrage.third_order_book.ask_hash[9][0].to_f.round(8) %></td>
          <td><%= @arbitrage.third_order_book.ask_hash[9][1].round(4) %></td>
        </tr>        
        </table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <span class="navbar-brand" href="#">Algocoin</span>
      <% end %>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=<%= cp(root_path) %>><%= link_to 'Accueil', root_path %><span class="sr-only">(current)</span></li>
        <li class=<%= cp(arbitrages_path) %>><%= link_to 'Arbitrages', arbitrages_path %></a></li>
        <li class=<%= cp(trades_path) %>><%= link_to 'Trades', trades_path %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">List of...<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to '...currencies', lists_of_currencies_path%></li>
            <li><%= link_to '...pairs', lists_of_pairs_path%></li>
            <li><%= link_to '...trios', lists_of_trios_path%></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Compte <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Editer mon compte', edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to 'Se connecter', new_user_session_path %></li>
              <li><%= link_to 'Nouveau compte', new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js' %>
  <%= javascript_include_tag '//cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js' %>
  <%= javascript_include_tag '//cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js' %>
  <%= javascript_include_tag '//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js' %>

</html>

app/views/lists/of_currencies.html.erb
<div class="container">
  <h1>List of currencies</h1>
  <p>Voici la liste de toutes les currencies disponibles sur Poloniex</p>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
      </tr>
    </thead>
    <% @currencies.each do |c| %>
    <tr>
      <td><%= c.id %></td>
      <td class="background-grey"><%= c.code %></td>
      <td><%= c.name %></td>
    </tr>  
    <% end %>
  </table>
</div>

app/views/lists/of_pairs.html.erb
<div class="container">
  <h1>List of pairs</h1>
  <p>Voici la liste de toutes les paires disponibles sur Poloniex</p>

  <table>
    <thead>
      <tr>
        <th></th>
        <th colspan="2">Currency 1</th>
        <th colspan="2">Currency 2</th>
      </tr>
      <tr>
        <th>ID</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
    </thead>
    <% n = 1 %>
    <% @pairs.each do |pair| %>
    <tr>
      <td><%= n %></td>
      <td class="background-grey"><%= pair.first_currency.code %></td>
      <td><%= pair.first_currency.name %></td>
      <td class="background-grey"><%= pair.second_currency.code %></td>
      <td><%= pair.second_currency.name %></td>
    </tr>  
    <% n += 1 %>
    <% end %>
  </table>
</div>

app/views/lists/of_trios.html.erb
<div class="container">
  <h1>List of trios</h1>
  <p>Voici la liste de toutes les trios où des arbitrages peuvent être testés sur Poloniex</p>

  <table>
    <thead>
      <tr>
        <th></th>
        <th colspan="2">Currency 1</th>
        <th colspan="2">Currency 2</th>
        <th colspan="2">Currency 3</th>
      </tr>
      <tr>
        <th>ID</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
        <th class="background-grey">Code</th>
        <th>Nom</th>
      </tr>
    </thead>
    <% n = 1 %>
    <% @trios.each do |trio| %>
    <tr>
      <td><%= n %></td>
      <td class="background-grey"><%= trio.first_currency.code %></td>
      <td><%= trio.first_currency.name%></td>
      <td class="background-grey"><%= trio.second_currency.code %></td>
      <td><%= trio.second_currency.name%></td>
      <td class="background-grey"><%= trio.third_currency.code %></td>
      <td><%= trio.third_currency.name%></td>
    </tr> 
    <% n += 1 %> 
    <% end %>
  </table>
</div>

app/views/pages/home.html.erb
<div class="container">

  <h1>Hello algocoin team !</h1>
  <p>C'est ici que tout va se paser, hiha !</p>
  <p>Sur la home page, ici donc, je vais mettre une to-do list que je vais faire avancer pour que vous sachiez ce que je fais.</p>
  <p>Et en back il va se passer plein de choses... Mais bon d'ici à ce qu'on puisse le visualiser ça va prendre un peu de temps.</p>



  <h2>To do list</h2>
  <ul>
    <li>Mettre en place ccxt sur l'app</li>
    <li>Bug: les ordres ne passent pas, probablement un problème de value et amount</li>
    <li>Ecrire des logs</li>
    <li>Create a script to get rid of all the shitcoins accidently collected</li>
  </ul>

  <h2>Done !</h2>
  <ul>
    <li>Créer une app Rails</li>
    <li>La déployer sur Heroku</li>
    <li>Installer Bootstrap</li>
    <li>Créer un modèle de Currencies</li>
    <li>Seed la base des currencies</li>
    <li>Créer les modèles de duos et trios</li>
    <li>Seed les modèles de duos et trios</li>
    <li>Créer des relationships entre models <em>(désolée ça a été super long!!)</em></li>
    <li>Créer les modèles OrderBook</li>
    <li>Créer le modèle Arbitrage</li>
    <li>Mettre en place le worker pour les OrderBook</li>
    <li>Modifier le précédent worker pour ajouter les arbitrages</li>
    <li>Mettre en place une view qui analyse les résultats</li>
    <li>Faire de la data viz pour les résultats des arbitrages ou mettre en place des exports csv</li>
    <li>Rajouter des views pour le détail de chaque arbitrage avec le détail de chacun des trois order book</li>
    <li>Mettre en place un accès avec account à l'app</li>
    <li>Bloquer l'accès si pas log out à certaines pages</li>
    <li>Mettre un mot de passe pour inscription</li>
    <li>Rajouter le pseudo des users</li>
    <li>Mettre le calcul du Worst Ratio dans le scrapper</li>
  </ul>


</div>

<script type="text/javascript" src="https://unpkg.com/ccxt">
  console.log (ccxt.exchanges)
</script>

app/views/trades/index.html.erb
<div class="container">
  <h1>Analyse des trades</h1>

  <p>Nous avons enregistré <%= @trades.count %> trades !</p>

  <table class="table table-condensed table-hover" id="trades">
    <thead>
      <tr>
        <th>Id</th>
        <th>Type</th>
        <th>Pair</th>
        <th>Rate</th>
        <th>Amount</th>
        <th>Total</th>
        <th>Fee</th>
        <th>Arbitrage ID</th>
        <th>Trio</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.id %></td>
        <td><%= trade.buy_or_sell %></td>
        <td><%= trade.pair.first_currency.code %> > <%= trade.pair.second_currency.code %></td>
        <td><%= trade.rate %></td>
        <td><%= trade.amount %></td>
        <td><%= trade.total %></td>
        <td><%= trade.fee %></td>
        <td><%= link_to trade.arbitrage.id, trade.arbitrage %></td>
        <td><%= trade.arbitrage.trio.first_currency.code%> > <%= trade.arbitrage.trio.second_currency.code%> > <%= trade.arbitrage.trio.third_currency.code%></td>
        <td><%= trade.created_at %></td>
      </tr>
      
      <% end %>
    </tbody>
  </table>
    
</div>